version: '3.8'

services:
  postgres:
    image: 'postgres:14.1-alpine'
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend_network

  redis:
    image: 'redis:6.2.6-alpine'
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend_network

networks:
  backend_network:
