DELETE FROM brands CASCADE;
DELETE FROM products CASCADE;
DELETE FROM product_images CASCADE;
DELETE FROM sizes CASCADE;

INSERT INTO brands (description, name)
VALUES ('Shoes brand', 'Nike'),
       ('Clothing brand', 'Adidas'),
       ('Sportswear brand', 'Under Armour'),
       ('Fashion brand', 'Gucci'),
       ('Luxury brand', 'Chanel'),
       ('Casual wear brand', 'Levi''s'),
       ('Streetwear brand', 'Supreme'),
       ('Swimwear brand', 'Speedo'),
       ('Formal wear brand', 'Armani'),
       ('Accessory brand', 'Ray-Ban'),
       ('Outdoor gear brand', 'The North Face'),
       ('Athletic apparel brand', 'Puma'),
       ('Skateboard brand', 'Vans'),
       ('Surf brand', 'Quiksilver'),
       ('Snowboard brand', 'Burton'),
       ('Sneaker brand', 'Reebok'),
       ('Running brand', 'New Balance'),
       ('Luxury fashion brand', 'Hermes'),
       ('High-end fashion brand', 'Prada'),
       ('Skincare brand', 'Lancome');

INSERT INTO products (description, name, price, season_type, brand_id)
VALUES ('A warm jacket for cold weather', 'Winter jacket', 199.99, 'WINTER', 1),
       ('A pair of skinny jeans', 'Skinny jeans', 59.99, 'AUTUMN', 2),
       ('A comfortable t-shirt for everyday wear', 'T-shirt', 19.99, 'SUMMER', 3),
       ('A classic dress shirt for formal occasions', 'Dress shirt', 137.50, 'MULTI_SEASON', 4),
       ('A cozy sweater for chilly days', 'Sweater', 79.99, 'WINTER', 1),
       ('A lightweight windbreaker for outdoor activities', 'Windbreaker', 49.99, 'SPRING', 2),
       ('A flowy sundress for the beach', 'Sundress', 29.99, 'SUMMER', 3),
       ('A wool skirt for work', 'Wool skirt', 89.99, 'AUTUMN', 4),
       ('A pair of leather boots', 'Leather boots', 149.99, 'WINTER', 5),
       ('A puffy down jacket for extreme cold', 'Down jacket', 249.99, 'WINTER', 2),
       ('A pair of cargo shorts for hiking', 'Cargo shorts', 39.99, 'SUMMER', 3),
       ('A casual hoodie for lounging', 'Hoodie', 59.99, 'MULTI_SEASON', 4),
       ('A linen shirt for hot weather', 'Linen shirt', 69.99, 'SUMMER', 1),
       ('A pair of suede ankle boots', 'Suede boots', 119.99, 'AUTUMN', 5),
       ('A warm wool coat for dressy occasions', 'Wool coat', 299.99, 'WINTER', 3),
       ('A pair of denim shorts for summer', 'Denim shorts', 29.99, 'SUMMER', 2),
       ('A classic blazer for work or events', 'Blazer', 179.99, 'MULTI_SEASON', 4),
       ('A cotton tunic for casual wear', 'Cotton tunic', 49.99, 'SPRING', 1),
       ('A pair of leather loafers', 'Loafers', 129.99, 'MULTI_SEASON', 5),
       ('A waterproof raincoat for wet weather', 'Raincoat', 99.99, 'SPRING', 2),
       ('A pair of athletic leggings', 'Athletic leggings', 49.99, 'MULTI_SEASON', 3),
       ('A cozy fleece pullover for outdoor activities', 'Fleece pullover', 69.99, 'AUTUMN', 4),
       ('A silk blouse for dressy occasions', 'Silk blouse', 89.99, 'MULTI_SEASON', 1),
       ('A pair of suede pumps for work or events', 'Suede pumps', 149.99, 'MULTI_SEASON', 5),
       ('A warm jacket for cold weather', 'Winter jacket', 199.99, 'WINTER', 1),
       ('A pair of skinny jeans', 'Skinny jeans', 59.99, 'AUTUMN', 2),
       ('A comfortable t-shirt for everyday wear', 'T-shirt', 19.99, 'SUMMER', 3),
       ('A classic dress shirt for formal occasions', 'Dress shirt', 137.50, 'MULTI_SEASON', 4),
       ('A pair of running shoes', 'Running shoes', 99.99, 'MULTI_SEASON', 5),
       ('A stylish watch for men', 'Men''s watch', 299.99, 'MULTI_SEASON', 6),
       ('A cozy sweater for the winter', 'Winter sweater', 79.99, 'WINTER', 7),
       ('A fashionable handbag', 'Handbag', 499.99, 'MULTI_SEASON', 8),
       ('A trendy pair of sunglasses', 'Sunglasses', 149.99, 'SUMMER', 9),
       ('A chic evening gown', 'Evening gown', 999.99, 'MULTI_SEASON', 10),
       ('A pair of hiking boots', 'Hiking boots', 129.99, 'AUTUMN', 1),
       ('A pair of flip-flops for the beach', 'Flip-flops', 29.99, 'SUMMER', 2),
       ('A classic leather belt', 'Leather belt', 49.99, 'MULTI_SEASON', 3),
       ('A warm wool scarf', 'Wool scarf', 39.99, 'WINTER', 4),
       ('A stylish bomber jacket', 'Bomber jacket', 179.99, 'MULTI_SEASON', 5),
       ('A pair of high-waisted shorts', 'High-waisted shorts', 69.99, 'SUMMER', 6),
       ('A pair of leather loafers', 'Loafers', 249.99, 'MULTI_SEASON', 7),
       ('A comfortable hoodie', 'Hoodie', 89.99, 'AUTUMN', 8),
       ('A pair of designer boots', 'Designer boots', 599.99, 'WINTER', 9),
       ('A classic polo shirt', 'Polo shirt', 99.99, 'SUMMER', 10);

INSERT INTO product_images (image_url, product_id)
VALUES ('https://example.com/image1.jpg', 1),
       ('https://example.com/image2.jpg', 1),
       ('https://example.com/image3.jpg', 2),
       ('https://example.com/image4.jpg', 3),
       ('https://example.com/image5.jpg', 4),
       ('https://example.com/image6.jpg', 4),
       ('https://example.com/image7.jpg', 4),
       ('https://example.com/image8.jpg', 5),
       ('https://example.com/image9.jpg', 6),
       ('https://example.com/image10.jpg', 7),
       ('https://example.com/image11.jpg', 7),
       ('https://example.com/image12.jpg', 8),
       ('https://example.com/image13.jpg', 9),
       ('https://example.com/image14.jpg', 10),
       ('https://example.com/image15.jpg', 10),
       ('https://example.com/image16.jpg', 11),
       ('https://example.com/image17.jpg', 12),
       ('https://example.com/image18.jpg', 13),
       ('https://example.com/image19.jpg', 13),
       ('https://example.com/image20.jpg', 14);

INSERT INTO sizes (size_value, quantity, product_id)
VALUES (36, 10, 1),
       (37, 8, 1),
       (38, 12, 1),
       (39, 6, 1),
       (40, 20, 1),
       (41, 14, 1),
       (42, 18, 1),
       (43, 10, 1),
       (44, 8, 1),
       (36, 15, 2),
       (38, 10, 2),
       (40, 20, 2),
       (42, 12, 2),
       (36, 15, 3),
       (38, 10, 3),
       (40, 20, 3),
       (42, 12, 3),
       (36, 15, 4),
       (38, 10, 4),
       (40, 20, 4),
       (42, 12, 4),
       (44, 8, 4),
       (36, 15, 5),
       (38, 10, 5),
       (40, 20, 5),
       (42, 12, 5),
       (36, 15, 6),
       (38, 10, 6),
       (40, 20, 6),
       (42, 12, 6),
       (36, 15, 7),
       (38, 10, 7),
       (40, 20, 7),
       (42, 12, 7),
       (36, 15, 8),
       (38, 10, 8),
       (40, 20, 8),
       (42, 12, 8),
       (36, 15, 9),
       (38, 10, 9),
       (40, 20, 9),
       (42, 12, 9),
       (36, 15, 10),
       (38, 10, 10),
       (40, 20, 10),
       (42, 12, 10),
       (40, 5, 26),
       (42, 8, 26),
       (38, 2, 27),
       (39, 6, 27),
       (40, 10, 27),
       (41, 5, 27),
       (42, 2, 27),
       (36, 3, 28),
       (37, 6, 28),
       (38, 8, 28),
       (39, 12, 28),
       (40, 10, 28),
       (41, 4, 28),
       (42, 2, 28),
       (36, 2, 29),
       (37, 4, 29),
       (38, 6, 29),
       (39, 8, 29),
       (40, 10, 29),
       (41, 4, 29),
       (42, 2, 29);


